# Generated by Django 3.0 on 2020-12-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
