# Generated by Django 3.0 on 2020-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_mango'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=500)),
                ('desrciption', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('author', models.CharField(max_length=100)),
                ('blogtext', models.CharField(max_length=1000)),
            ],
        ),
    ]
