# Generated by Django 3.0 on 2021-01-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210108_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogsubject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogtext',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogtitle',
            new_name='title',
        ),
    ]
